# Generated by Django 3.0.4 on 2020-03-10 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=90)),
                ('l_name', models.CharField(max_length=90)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=30)),
                ('phone', models.IntegerField()),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='login/static')),
            ],
        ),
    ]
