# Generated by Django 3.0.3 on 2020-03-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20200313_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.CharField(default=0, max_length=90),
        ),
    ]
