# Generated by Django 3.0.3 on 2020-03-13 21:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20200313_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.IntegerField(validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '01234567890'. Up to 11 digits allowed.", regex='^(010|011|012)[0-9]{7}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.CharField(choices=[('A', 'active'), ('D', 'disable')], default='D', max_length=2),
        ),
    ]
