# Generated by Django 3.0.3 on 2020-03-13 22:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20200313_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.IntegerField(validators=[django.core.validators.RegexValidator('^(010|011|012)[0-9]{8}$', message='number must be 01112342342')]),
        ),
    ]
