# Generated by Django 3.0.3 on 2020-03-14 00:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20200313_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^(010|011|012)[0-9]{8}$', message='number must be 01112342342')]),
        ),
    ]
