# Generated by Django 3.0.3 on 2020-03-20 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20200320_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='login/static/3de9bb99-260d-4fc1-8666-82c9a5fa3201'),
        ),
    ]
