# Generated by Django 3.0.3 on 2020-03-20 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20200320_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='login/static/0ffff72d-cb75-4b19-8c75-2bd5a6c9c182'),
        ),
    ]
