# Generated by Django 3.0.3 on 2020-03-22 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_auto_20200321_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='login/static/3b454ce6-46ac-4ddd-b035-591a6ab974b9'),
        ),
    ]
