# Generated by Django 3.0.3 on 2020-03-22 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_auto_20200322_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='login/static/4740b242-e1cb-45db-8159-bad840f01fbb'),
        ),
    ]
