# Generated by Django 3.0.3 on 2020-03-20 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20200320_2143'),
        ('dataAdd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataadd',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.User'),
        ),
    ]
