# Generated by Django 3.0.3 on 2020-03-22 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataAdd', '0002_auto_20200320_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataadd',
            name='birthdate',
            field=models.DateTimeField(blank=True),
        ),
    ]
