# Generated by Django 3.0.3 on 2020-03-22 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataAdd', '0003_auto_20200322_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataadd',
            name='birthdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
