# Generated by Django 3.0.3 on 2020-03-21 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_projects', '0002_auto_20200320_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_show',
            field=models.BooleanField(default=0),
        ),
    ]
