# Generated by Django 3.0.3 on 2020-03-22 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_projects', '0003_projects_project_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='img',
            field=models.ImageField(upload_to='media/projects/img'),
        ),
    ]
